Dockerインストール用スクリプト追加
WaitShimizu/EZTaxCraft_flask pull request #21
Opened 2024-08-28 07:00 UTC by NatsukiShimizu

Dockerインストール用スクリプト追加 #20

2024-08-28 07:06 UTC, WaitShimizu requested changes
指摘があります。対応お願いします。

2024-08-28 07:06 UTC, WaitShimizu commented on scripts/INSTALL_DOCKER.sh
> +    IS_REO_RESTART=1
変数名が違います。
誤：IS_REO_RESTART=1
正：IS_REQ_RESTART=1

2024-08-28 07:06 UTC, WaitShimizu commented on scripts/INSTALL_DOCKER.sh
> +    echo -e "'docker' command exists."
この行の1行後ろに以下の内容を挿入してください。
IS_REQ_RESTART=0

2024-08-28 07:06 UTC, WaitShimizu commented on scripts/INSTALL_DOCKER.sh
> +    IS_REO_RESTART=1
変数名が違います。
誤：IS_REO_RESTART=1
正：IS_REQ_RESTART=1

2024-08-28 07:06 UTC, WaitShimizu commented on scripts/INSTALL_DOCKER.sh
> +    echo -e "'docker-compose' command exists."
この行の1行後ろに以下の内容を挿入してください。
IS_REQ_RESTART=0

2024-08-28 07:45 UTC, NatsukiShimizu commented on scripts/INSTALL_DOCKER.sh
> +    IS_REO_RESTART=1
変数名修正しました。

2024-08-28 07:45 UTC, NatsukiShimizu commented on scripts/INSTALL_DOCKER.sh
> +    echo -e "'docker' command exists."
追加しました。

2024-08-28 07:45 UTC, NatsukiShimizu commented on scripts/INSTALL_DOCKER.sh
> +    IS_REO_RESTART=1
変数名修正しました。

2024-08-28 07:45 UTC, NatsukiShimizu commented on scripts/INSTALL_DOCKER.sh
> +    echo -e "'docker-compose' command exists."
追加しました。

2024-09-23 07:37 UTC, WaitShimizu approved these changes
指摘はありません。

2024-09-24 06:38 UTC, merged